# This workflow will build a MuleSoft project and deploy to CloudHub
name: TestCICD Pipeline
on:
  push:
    branches:    
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'   # excludes master
jobs:
  variables:
    runs-on: ubuntu-latest
    steps:    
    - name: Display Variables
      env:
        ANYPOINT_PASSWORD: ${{ secrets.ANYPOINT_PASSWORD }}
      run: |
        echo "INICIO"
        echo "ANYPOINT_APIVERSION"
        echo ${{secrets.ANYPOINT_APIVERSION}} | sed 's/./& /g'
        echo "ANYPOINT_ENVIRONMENT"
        echo ${{secrets.ANYPOINT_ENVIRONMENT}} | sed 's/./& /g'
        echo "ANYPOINT_USERNAME"
        echo ${{secrets.ANYPOINT_USERNAME}} | sed 's/./& /g'
        echo "ANYPOINT_PASSWORD"
        echo ${{secrets.ANYPOINT_PASSWORD}} | sed 's/./& /g'
        echo "ANYPOINT_REGION"
        echo ${{secrets.ANYPOINT_REGION}} | sed 's/./& /g'
        echo "ANYPOINT_USERNAME"
        echo ${{secrets.ANYPOINT_USERNAME}} | sed 's/./& /g'
        echo "ANYPOINT_VERSION"
        echo ${{secrets.ANYPOINT_VERSION}} | sed 's/./& /g'
        echo "ANYPOINT_WORKERS"
        echo ${{secrets.ANYPOINT_WORKERS}} | sed 's/./& /g'
        echo "ANYPOINT_WORKERTYPE"
        echo ${{secrets.ANYPOINT_WORKERTYPE}} | sed 's/./& /g'
        echo "REPO_NAME"
        echo "REPO_NAME=${{ github.event.repository.name }}"
        echo "FIN"
